/* eslint-disable */
/**
 * @fileoverview gRPC-Web generated client stub for timeseries
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.4.1
// 	protoc              v3.12.4
// source: timeseries.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');

const proto = {};
proto.timeseries = require('./timeseries_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.timeseries.TimeSeriesServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.timeseries.TimeSeriesServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.timeseries.TimeSeriesRequest,
 *   !proto.timeseries.TimeSeries>}
 */
const methodDescriptor_TimeSeriesService_GetTimeSeries = new grpc.web.MethodDescriptor(
  '/timeseries.TimeSeriesService/GetTimeSeries',
  grpc.web.MethodType.UNARY,
  proto.timeseries.TimeSeriesRequest,
  proto.timeseries.TimeSeries,
  /**
   * @param {!proto.timeseries.TimeSeriesRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.timeseries.TimeSeries.deserializeBinary
);


/**
 * @param {!proto.timeseries.TimeSeriesRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.timeseries.TimeSeries)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.timeseries.TimeSeries>|undefined}
 *     The XHR Node Readable Stream
 */
proto.timeseries.TimeSeriesServiceClient.prototype.getTimeSeries =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/timeseries.TimeSeriesService/GetTimeSeries',
      request,
      metadata || {},
      methodDescriptor_TimeSeriesService_GetTimeSeries,
      callback);
};


/**
 * @param {!proto.timeseries.TimeSeriesRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.timeseries.TimeSeries>}
 *     Promise that resolves to the response
 */
proto.timeseries.TimeSeriesServicePromiseClient.prototype.getTimeSeries =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/timeseries.TimeSeriesService/GetTimeSeries',
      request,
      metadata || {},
      methodDescriptor_TimeSeriesService_GetTimeSeries);
};


module.exports = proto.timeseries;

